"""Print the DB2 for i CREATE TABLE statements for the forecast, sales and
suggested tables, from the one definition in src/tables.py. The IBM i
project commits the output as its schema file.

    PYTHONPATH=. python tools/ibmi/ddl.py [--library MYLIB] > forecast_tables.sql

The library defaults to IBMI_LIBRARY from the environment. Table names are
upper case, as DB2 for i stores them."""
import argparse, os
from src import tables

p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
p.add_argument("--library", default=os.environ.get("IBMI_LIBRARY", "MYLIB"))
a = p.parse_args()

print("-- Generated by tools/ibmi/ddl.py in github.com/wesGates/demand-forecasting from src/tables.py.")
print("-- Do not edit; change src/tables.py and regenerate.")
for table in tables.TABLES:
    print()
    print(tables.ddl(table, "db2", qualified=f"{a.library}.{table.upper()}") + ";")
